---
driver:
  name: lxd_cli
## nfsd requires extra privileges. See README.md
#  profile: unconfined	= profile not existing. security.privileged=true ?
# config:
#    security.privileged: true	= valid but still can't mount
#    lxc.aa_profile: unconfined	 = not recognized

transport:
  name: sftp

provisioner:
  name: ansible_playbook
  roles_path: ../
  hosts: test-kitchen
#  ansible_verbose: true
  ansible_verbose: false
  ansible_verbosity: 4
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
#  require_chef_omnibus: false
  require_ansible_omnibus: true
#  require_chef_for_busser: false
  enable_yum_epel: true
  ansible_connection: ssh

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-14.04
#  - name: ubuntu-12.04
#  - name: centos-7
#  - name: centos-6
#  - name: alpine-3.4

suites:
#  - name: default
#    run_list:
#    attributes:

  - name: smb
    run_list:
    attributes:
        servertype: smb
    includes:
      - ubuntu-16.04
      - ubuntu-14.04
      - centos-7
    provisioner:
      name: ansible_playbook
      playbook: test/integration/smb/smb.yml

