---
## from https://github.com/geerlingguy/ansible-role-apache/blob/master/.travis.yml
sudo: required

env:
# last working https://travis-ci.org/juju4/ansible-fileserver/jobs/289719255
#  - distribution: centos
#    version: 6
#    init: /sbin/init
#    run_opts: ""
#    suite: default
#    ansible_version: 2.4.0.0
#    cryptography_version: 2.1.1
  - distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default
    ansible_version: 2.4.0.0
    cryptography_version: 2.1.1
  - distribution: ubuntu
    version: 16.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default
    ansible_version: 2.4.0.0
    cryptography_version: 2.1.1
  - distribution: ubuntu
    version: 14.04
    init: /sbin/init
    run_opts: ""
    suite: default
    ansible_version: 2.4.0.0
    cryptography_version: 2.1.1
#  - distribution: ubuntu
#    version: 12.04
#    init: /sbin/init
#    run_opts: ""
#    suite: default
#    ansible_version: 2.4.0.0
  - distribution: centos
    version: 7
    init: /usr/lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: smb
    ansible_version: 2.4.0.0
    cryptography_version: 2.1.1
  - distribution: ubuntu
    version: 16.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: smb
    ansible_version: 2.4.0.0
    cryptography_version: 2.1.1
## past ansible versions
  - distribution: ubuntu
    version: 16.04
    init: /lib/systemd/systemd
    run_opts: "'--privileged --volume=/sys/fs/cgroup:/sys/fs/cgroup:ro'"
    suite: default
    ansible_version: 2.3.0.0
    cryptography_version: 2.1.1

services:
  - docker

before_install:
  # - sudo apt-get update
  # Pull container
  - 'sudo docker pull ${distribution}:${version}'
  - env
  - pwd
  - find -ls
  - "[ -f get-dependencies.sh ] && sh -x get-dependencies.sh"
  - cp test/travis/initctl_faker test/
  # Customize container
  - 'sudo docker build --rm=true --file=test/travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible test'

script:
  - container_id=$(mktemp)
    # Run container in detached state
  - 'sudo docker run --detach --volume="${PWD%/*}":/etc/ansible/roles:ro ${run_opts} ${distribution}-${version}:ansible "${init}" > "${container_id}"'

  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm pip install --upgrade pip'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm pip install cryptography==${cryptography_version}'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm pip install ansible==${ansible_version}'
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible --version'

  # Ansible syntax check.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.fileserver/test/integration/${suite}/default.yml --syntax-check'

  # Test role.
  - 'sudo docker exec --tty "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.fileserver/test/integration/${suite}/default.yml'

  # Test role idempotence.
# known fail: Ensure appropriate services are enabled
  - >
    sudo docker exec "$(cat ${container_id})" env TERM=xterm ansible-playbook /etc/ansible/roles/juju4.fileserver/test/integration/${suite}/default.yml
    | tee /tmp/idempotency.log
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && cat /tmp/idempotency.log && exit 0)

after_failure:
  # Check what happened on systemd systems.
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l --no-pager status rpcbind.service'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l --no-pager status nfs-kernel-server.service'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l --no-pager status samba.service'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm systemctl -l --no-pager status smb.service'
  - 'docker exec --tty "$(cat ${container_id})" env TERM=xterm journalctl -xe --no-pager'

after_script:
  # Clean up
  - 'sudo docker stop "$(cat ${container_id})"'

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
