---

- block:
    - name: RedHat | nfs file server packages install
      yum:
        name: nfs-utils
        state: present
    - name: Redhat | Ensure services are running and enabled on boot.
      service: name=nfs-server state=started enabled=yes
      when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
  when: (servertype is defined and servertype == 'nfs')

- block:
    - name: RedHat | samba file server packages install
      yum:
        name:
        - samba
        - samba-common
        state: present
    - name: Redhat | Ensure services are running and enabled on boot.
      service: name={{ item }} state=started enabled=yes
      with_items:
        - smb
        - nmb
      when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")
  when: (servertype is defined and servertype == 'smb')
