---

- name: Verify
  hosts: fileserver
  pre_tasks:
    - name: Debian | set facts
      set_fact:
        verify_pkgs:
          - nfs-common
          - nfs-kernel-server
      when: ansible_os_family == "Debian"
    - name: RedHat | set facts
      set_fact:
        verify_pkgs:
          - nfs-utils
      when: ansible_os_family == "RedHat"
  tasks:
    - name: Gather package facts
      package_facts:
        manager: auto
    - name: Validate that needed packages are present
      assert:
        that: ansible_facts.packages[item]
      with_items: "{{ verify_pkgs }}"

    - name: Check /opt/share
      stat:
        path: /opt/share
      register: share
    - name: Validate share directory
      assert:
        that: share.stat.exists and share.stat.isdir and share.stat.pw_name == 'nobody'

    - name: Fetch content of /etc/exports
      slurp:
        src: /etc/exports
      register: exports
    - name: Validate NFS exports
      assert:
        that: >
          "'/opt/share 192.168.200.0/255.255.255.0(rw)' in exports['content'] | b64decode"
